article/urls.py
from django.urls import path
from . import views

# 正在部署的应用的名称
app_name = 'blog'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('time-line/', views.time_line, name='time_line'),
    path('increase-likes/<int:id>/', views.increase_likes, name='increase_likes'),
    path('categories_list/', views.categories_list, name='categories_list'),
    path('courses_list/', views.courses_list, name='courses_list'),
    path('', views.index, name='index'),
    path('<slug:slug>/', views.article_detail, name='article_detail'),
    path('categories/<slug:slug>/', views.category, name='category'),
    path('courses/<slug:slug>/', views.courses, name='courses'),
    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    path('tags/<slug:slug>/', views.tag, name='tag'),
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from article import views

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('article/', include('article.urls', namespace='article')),
                  path('', views.index, name='index'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
import re
import os
import uuid

import markdown
from mdeditor.fields import MDTextField
from uuslug import slugify

from django.urls import reverse

from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


def articleimage_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    return os.path.join("articleimage", filename)


# 文章关键字
class Keyword(models.Model):
    name = models.CharField('文章关键词', max_length=20)

    class Meta:
        verbose_name = '关键词'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name


# 文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240,
                                   help_text='用来作为SEO中description,长度参考SEO标准')

    def save(self, *args, **kwargs):
        if not self.id or not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name


# 文章分类
class Category(models.Model):
    name = models.CharField('文章分类', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240,
                                   help_text='用来作为SEO中description,长度参考SEO标准')

    def save(self, *args, **kwargs):
        if not self.id or not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name


# 教程
class Course(models.Model):
    name = models.CharField('教程', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240,
                                   help_text='用来作为SEO中description,长度参考SEO标准')

    def save(self, *args, **kwargs):
        if not self.id or not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = '教程'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name


# 文章
class Article(models.Model):
    # IMG_LINK = '/static/blog/img/summary.png'
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)
    title = models.CharField(max_length=150, verbose_name='文章标题')
    slug = models.SlugField(max_length=250, unique=True)
    summary = models.TextField('文章摘要', max_length=230, default='文章摘要等同于网页description内容，请务必填写...')
    body = MDTextField(verbose_name='文章内容')
    image = models.ImageField('图片', upload_to=articleimage_directory_path)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    views = models.IntegerField('阅览量', default=0)
    # 新增点赞数统计
    likes = models.PositiveIntegerField(default=0)

    is_top = models.BooleanField('置顶', default=False)

    category = models.ForeignKey(Category, verbose_name='文章分类', on_delete=models.PROTECT)
    course = models.ForeignKey(Course, verbose_name='课程', on_delete=models.PROTECT, blank=True, null=True)
    tags = models.ManyToManyField(Tag, verbose_name='标签')
    keywords = models.ManyToManyField(Keyword, verbose_name='文章关键词',
                                      help_text='文章关键词，用来作为SEO中keywords，最好使用长尾词，3-4个足够')

    def save(self, *args, **kwargs):
        if not self.id or not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article_detail', kwargs={'slug': self.slug})

    def body_to_markdown(self):
        return markdown.markdown(self.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

    def update_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_pre(self):
        return Article.objects.filter(id__lt=self.id).order_by('-id').first()

    def get_next(self):
        return Article.objects.filter(id__gt=self.id).order_by('id').first()


# 幻灯片
class Carousel(models.Model):
    number = models.IntegerField('编号', help_text='编号决定图片播放的顺序，图片不要多于5张')
    title = models.CharField('标题', max_length=20, blank=True, null=True, help_text='标题可以为空')
    content = models.CharField('描述', max_length=80)
    image = models.ImageField('轮播图', upload_to='banner/%Y%m')
    # img_url = models.CharField('图片地址', max_length=200)
    url = models.CharField('跳转链接', max_length=256, default='#', help_text='图片跳转的超链接，默认#表示不跳转')

    class Meta:
        verbose_name = '图片轮播'
        verbose_name_plural = verbose_name
        # 编号越小越靠前，添加的时间约晚约靠前
        ordering = ['number', '-id']

    def __str__(self):
        return self.content[:25]


# 评论
class Comment(models.Model):
    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
        verbose_name='文章评论'
    )
    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.body[:20]

article/forms.py
from django import forms
from .models import Comment


# 评论表单
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

article/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.http import HttpResponse
# from django.core.paginator import Paginator

from .models import Article, Carousel, Category, Tag, Comment,Course
from .forms import CommentForm

from utils.pagination import Pagination


def index(request):
    articles = Article.objects.all()[0:10]  # 默认首页显示最新5篇文章
    allcategory = Category.objects.all()
    carousels = Carousel.objects.all()
    articles_top = Article.objects.all().filter(is_top=True)
    context = {'articles': articles, 'carousels': carousels, 'articles_top': articles_top,
               'allcategory': allcategory}
    return render(request, 'blog/index.html', context)


def article_detail(request, slug):
    # 取出相应的文章
    article = Article.objects.get(slug=slug)
    article.update_views()
    article.body = article.body_to_markdown()
    comments = Comment.objects.filter(article=article)
    # 引入评论表单
    comment_form = CommentForm()
    cate = article.category
    post_list = Article.objects.filter(category=cate).order_by('-create_date')[0:8]

    # 需要传递给模板的对象
    context = {'article': article, 'comments': comments, 'comment_form': comment_form, 'post_list': post_list}
    # 载入模板，并返回context对象
    return render(request, 'blog/article_detail.html', context)


def category(request, slug):
    # 记得在开始部分导入 Category 类
    cate = get_object_or_404(Category, slug=slug)
    title = cate.name
    des = cate.description
    post_list = Article.objects.filter(category=cate).order_by('-create_date')
    page = Pagination(request, post_list.count(), 15)
    return render(request, 'blog/list.html',
                  context={'post_list': post_list[page.start:page.end], 'title': title, 'des': des,
                           'page_html': page.page_html})


def courses(request, slug):
    # 记得在开始部分导入 Category 类
    courses = get_object_or_404(Course, slug=slug)
    title = courses.name
    des = courses.description
    post_list = Article.objects.filter(course=courses).order_by('-create_date')
    page = Pagination(request, post_list.count(), 15)
    return render(request, 'blog/list.html',
                  context={'post_list': post_list[page.start:page.end], 'title': title, 'des': des,
                           'page_html': page.page_html})





def archive(request, year, month):
    post_list = Article.objects.filter(create_date__year=year,
                                       create_date__month=month,
                                       ).order_by('-create_date')
    title = str(year) + '年' + str(month) + '月文章'
    page = Pagination(request, post_list.count(), 15)
    return render(request, 'blog/list.html',
                  context={'post_list': post_list[page.start:page.end], 'title': title, 'page_html': page.page_html})


def tag(request, slug):
    # 记得在开始部分导入 Tag 类
    t = get_object_or_404(Tag, slug=slug)
    title = t.name
    des = t.description
    post_list = Article.objects.filter(tags=t).order_by('-create_date')
    page = Pagination(request, post_list.count(), 15)
    return render(request, 'blog/list.html',
                  context={'post_list': post_list[page.start:page.end], 'title': title, 'des': des,
                           'page_html': page.page_html})


def search(request):
    keyboard = request.GET.get('keyboard')

    if keyboard:
        post_list = Article.objects.filter(
            Q(title__icontains=keyboard) |
            Q(body__icontains=keyboard)
        )
    else:
        post_list = Article.objects.all()

    title = '包含' + keyboard + '的文章'
    des = keyboard
    page = Pagination(request, post_list.count(), 15)
    context = {'post_list': post_list[page.start:page.end], 'title': title, 'des': des, 'page_html': page.page_html}
    return render(request, 'blog/list.html', context)


# 时间轴
def time_line(request):
    articles = Article.objects.all()
    page = Pagination(request, articles.count(), 20)
    context = {'articles': articles[page.start:page.end], 'page_html': page.page_html}
    return render(request, 'blog/time-line.html', context)


def post_comment(request, article_id):
    """
    :param request:
    :param article_id: 文章id
    :return:
    """
    article = get_object_or_404(Article, id=article_id)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article = article
            new_comment.save()
            return redirect(article)
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    else:
        return HttpResponse("发表评论仅接受POST请求。")


def increase_likes(request, id):
    """
    点赞
    :param request:
    :param article_id: 文章id
    :return:
    """
    if request.method == 'POST':
        article = Article.objects.get(id=id)
        article.likes += 1
        article.save()
        return HttpResponse('success')


def categories_list(request):
    cate_list = Category.objects.all()
    return render(request, 'blog/categories_list.html',
                  context={'cate_list': cate_list})


def courses_list(request):
    cate_list = Course.objects.all()
    return render(request, 'blog/courses_list.html',
                  context={'cate_list': cate_list})

article/templates/blog/article_detail.html
{% extends "blog/base.html" %}
{% load static %}
{% load blog_extras %}
{% block title %}
    {{ article.title }}
{% endblock title %}
{% block keywords %}{% keywords_to_str article %}{% endblock keywords %}
{% block description %}{{ article.summary }}{% endblock description %}

{% block content %}
    <div class="wrapper">
        <main>
            <h2 class="place">您现在的位置是：<a href="{% url 'blog:index' %}">网站首页&gt;</a> <a href="#">{{ article.title }}</a>
            </h2>
            <div class="infosbox">
                <div class="newsview">
                    <h3 class="news_title">{{ article.title }}</h3>
                    <div class="bloginfo">
                        <ul>
                            <li class="author">{{ article.author }}</li>
                            <li class="lmname">{{ article.category }}</li>
                            <li class="timer">{{ article.create_date }}</li>
                            <li class="view">
                                {{ article.views }}人已阅读
                            </li>
                        </ul>
                    </div>
                    <div class="tags">
                        {% for tag in article.tags.all %}
                            <a href="{% url 'blog:tag' tag.slug %}" target="_blank">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                    <div class="news_about"><strong>简介</strong>{{ article.summary }}...
                    </div>
                    <div class="news_con">
                        {{ article.body|safe }}
                    </div>
                </div>
                <div class="share">
                    <p class="diggit"><a style="cursor:pointer" onclick="validate_is_like(
                            '{% url 'blog:increase_likes' article.id %}',{{ article.id }},{{ article.likes }})">很赞哦！</a>(<b
                            id="likes_number">{{ article.likes }}</b>)
                    </p>
                </div>

                <div class="nextinfo">
                    <p>上一篇：<a
                            href="{{ article.get_pre.get_absolute_url }}">{{ article.get_pre.title|default:'已经是第一篇了' }}
                    </a></p>
                    <p>下一篇：<a
                            href="{{ article.get_next.get_absolute_url }}">{{ article.get_next.title|default:'已经是最后一篇了' }}</a>
                    </p>
                </div>
                <div class="otherlink">
                    <h2>相关文章</h2>
                    <ul>
                        {% for article in post_list %}
                            <li><a href="{% url 'blog:article_detail' article.slug %}"
                                   title="{{ article.title }}">{{ article.title }}</a></li>

                        {% endfor %}

                    </ul>
                </div>

                <div>
                    <form
                            action="{% url 'blog:post_comment' article.id %}"
                            method="POST"
                    >
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="body">
                                <strong>
                                    我也要发言：
                                </strong>
                            </label>
                            <div>
                                {{ comment_form.media }}
                                {{ comment_form.body }}
                            </div>
                        </div>
                        <!-- 提交按钮 -->
                        <button type="submit" class="btn btn-primary ">发送</button>
                    </form>
                </div>
                <!-- 显示评论 -->
                <h4>共有{{ comments.count }}条评论</h4>
                <div>
                    {% for comment in comments %}
                        <hr>
                        <p>

                            <span style="color: green">
                    {{ comment.created|date:"Y-m-d H:i:s" }}
                </span> 时说：
                        </p>
                        <pre style="font-family: inherit; font-size: 1em;">
{{ comment.body|safe }}</pre>
                    {% endfor %}
                </div>
            </div>
        </main>
        {% include 'blog/sidebar.html' %}
    </div>
    <script>
        $(".django-ckeditor-widget").removeAttr('style');
    </script>


    <script src="{% static 'blog/js/csrf.js' %}"></script>
    <script>
        // 点赞功能主函数
        function validate_is_like(url, id, likes) {
            // 取出 LocalStorage 中的数据
            let storage = window.localStorage;
            const storage_str_data = storage.getItem("my_blog_data");
            let storage_json_data = JSON.parse(storage_str_data);
            // 若数据不存在，则创建空字典
            if (!storage_json_data) {
                storage_json_data = {}
            }
            ;
            // 检查当前文章是否已点赞。是则 status = true
            const status = check_status(storage_json_data, id);
            if (status) {
                layer.msg('已经点过赞了哟~');
                // 点过赞则立即退出函数
                return;
            } else {
                // 用 Jquery 找到点赞数量，并 +1
                $('#likes_number').text(likes + 1);
            }
            // 用 ajax 向后端发送 post 请求
            $.post(
                url,
                // post 只是为了做 csrf 校验，因此数据为空
                {},
                function (result) {
                    if (result === 'success') {
                        // 尝试修改点赞数据
                        try {
                            storage_json_data[id] = true;
                        } catch (e) {
                            window.localStorage.clear();
                        }
                        ;
                        // 将字典转换为字符串，以便存储到 LocalStorage
                        const d = JSON.stringify(storage_json_data);
                        // 尝试存储点赞数据到 LocalStorage
                        try {
                            storage.setItem("my_blog_data", d);
                        } catch (e) {
                            // code 22 错误表示 LocalStorage 空间满了
                            if (e.code === 22) {
                                window.localStorage.clear();
                                storage.setItem("my_blog_data", d);
                            }
                        }
                        ;
                    } else {
                        layer.msg("与服务器通信失败..过一会儿再试试呗~");
                    }

                }
            );
        };

        // 辅助点赞主函数，验证点赞状态
        function check_status(data, id) {
            // 尝试查询点赞状态
            try {
                if (id in data && data[id]) {
                    return true;
                } else {
                    return false;
                }
            } catch (e) {
                window.localStorage.clear();
                return false;
            }
            ;
        };
    </script>
{% endblock content %}

article/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="utf-8">
<head>
    <title>{% block title %}{% endblock title %}</title>
    <meta name="keywords" content="{% block keywords %}{% endblock keywords %}"/>
    <meta name="description"
          content="{% block description %}{% endblock description %}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'blog/css/base.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/index.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/m.css' %}" rel="stylesheet">
    <script src="{% static 'blog/js/jquery.min.js' %}"></script>
    <script src="{% static 'blog/js/hc-sticky.js' %}"></script>
    <script src="{% static 'blog/js/comm.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.js' %}"></script>
    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">
    <style>
        .codehilite {
            padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }
    </style>
</head>
<body>
{% include 'blog/header.html' %}
{% block content %}{% endblock content %}
{% include 'blog/footer.html' %}
<a href="#" class="cd-top">Top</a>
<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>
</body>
</html>

article/templates/blog/categories_list.html
{% extends "blog/base.html" %}
{% block title %}分类{% endblock title %}
{% block keywords %}Python学习，Google SEO ,Baidu SEO{% endblock keywords %}
{% block description %}Chenglulu个人博客，学习知识，分享知识{% endblock description %}
{% block content %}
    <div class="wrapper">
        <main>
            <h2 class="place">您现在的位置是：<a href="{% url 'blog:index' %}">网站首页</a>&gt; <a href="#">分类</a></h2>

            {% for cate in cate_list %}
                <div class="fengm">
                    <h3><span><a href="{% url 'blog:category' cate.slug %}"
                                 target="_blank">更多+</a></span>{{ cate.name }}</h3>
                    <div class="fpicbox">
                        <ul>
                            {% for ar in cate.article_set.all|slice:'0:3' %}
                                <li class="fpic"><a href="{{ ar.get_absolute_url }}" target="_blank"><img
                                        src="{{ ar.image.url }}"><i>{{ ar.title }}</i></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <ul class="fmnews">
                        <ul>
                            {% for ar in cate.article_set.all|slice:'3:' %}
                                <li><span>{{ ar.create_date }}</span> <a href="{{ ar.get_absolute_url }}">{{ ar.title }}</a></li>
                            {% endfor %}
                        </ul>

                    </ul>
                </div>
            {% endfor %}

        </main>
        {% include 'blog/sidebar.html' %}
    </div>

{% endblock content %}

article/templates/blog/courses_list.html
{% extends "blog/base.html" %}
{% block title %}分类{% endblock title %}
{% block keywords %}Python学习，Google SEO ,Baidu SEO{% endblock keywords %}
{% block description %}Chenglulu个人博客，学习知识，分享知识{% endblock description %}
{% block content %}
    <div class="wrapper">
        <main>
            <h2 class="place">您现在的位置是：<a href="{% url 'blog:index' %}">网站首页</a>&gt; <a href="#">分类</a></h2>

            {% for cate in cate_list %}
                <div class="fengm">
                    <h3><span><a href="{% url 'blog:courses' cate.slug %}"
                                 target="_blank">更多+</a></span>{{ cate.name }}</h3>
                    <div class="fpicbox">
                        <ul>
                            {% for ar in cate.article_set.all|slice:'0:3' %}
                                <li class="fpic"><a href="{{ ar.get_absolute_url }}" target="_blank"><img
                                        src="{{ ar.image.url }}"><i>{{ ar.title }}</i></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <ul class="fmnews">
                        <ul>
                            {% for ar in cate.article_set.all|slice:'3:' %}
                                <li><span>{{ ar.create_date }}</span> <a href="{{ ar.get_absolute_url }}">{{ ar.title }}</a></li>
                            {% endfor %}
                        </ul>

                    </ul>
                </div>
            {% endfor %}

        </main>
        {% include 'blog/sidebar.html' %}
    </div>

{% endblock content %}

article/templates/blog/footer.html
{% load static %}
<footer>
    <div class="footer">
        <div class="wxbox">
            <ul>
                <li><img src="{% static 'blog/images/mmqrcode1597044665429.png' %}"><span>我的微信</span></li>
                <li><img src="{% static 'blog/images/mmqrcode1597045074871.png' %}"><span>微信公众号</span></li>
            </ul>
        </div>
        <div class="bzjj">
            <h2>本站简介</h2>
            <p>GoogleSEO一些技巧,Python学习</p>
        </div>
        <div class="other">
            <h2>网站版权</h2>
            <p>本站所有主题/文章除标明原创外，均来自网络转载，版权归原作者所有，如果有侵犯到您的权益，请联系本站删除，谢谢！</p>
            <p>&nbsp;</p>
{#            <p>备案号：粤ICP备15025043号</p>#}
        </div>
    </div>
</footer>

article/templates/blog/header.html
{% load static %}
{% load blog_extras %}
<header id="header">
    <div class="navbar">
        <div class="topbox">
            <p class="welcome">如果重新开始，我会做什么?</p>
            <div class="searchbox">
                <div id="search_bar" class="search_bar">
                    <form id="searchform" action="{% url 'blog:search' %}" method="get" name="searchform">
                        <input class="input" placeholder="想搜点什么呢.." type="text" name="keyboard" id="keyboard">
                        <p class="search_ico"><span></span></p>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="header-navigation">
        <nav>
{#            <div class="logo"><a href="{% url 'my_blog:article_list' %}">Chenglulu个人博客</a></div>#}
{#            <h2 id="mnavh"><span class="navicon"></span></h2>#}
{#            <ul id="starlist">#}
{#                <li><a href="{% url 'my_blog:article_list' %}">网站首页</a></li>#}
{#                <li><a href="#">关于我</a></li>#}
{#                <li><a href="{% url 'my_blog:time_line' %}">时间轴</a></li>#}
{#                <li><a href="#">教程</a></li>#}
{#                <li class="menu"><a href="#">分类</a>#}
{#                    <ul class="sub">#}
{#                    {% show_categories_banner %}#}
{##}
{#                    </ul>#}
{#                </li>#}
{#            </ul>#}
            <div class="logo"><a href="{% url 'blog:index' %}">Chenglulu个人博客</a></div>
            <h2 id="mnavh"><span class="navicon"></span></h2>
            <ul id="starlist">
                <li><a href="{% url 'blog:index' %}">网站首页</a></li>
{#                <li><a href="#">关于我</a></li>#}
                <li><a href="{% url 'blog:time_line' %}">时间轴</a></li>
                <li><a href="{% url 'blog:courses_list' %}">教程</a></li>
                <li class="menu"><a href="{% url 'blog:categories_list' %}">分类</a>
                    <ul class="sub">
                    {% show_categories_banner %}
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</header>

article/templates/blog/list.html
{% extends "blog/base.html" %}
{% load blog_extras %}
{% block title %}
    {{ title }}
{% endblock title %}
{% block keywords %}{{ title }}{% endblock keywords %}
{% block description %}{{ des }}{% endblock description %}

{% block content %}
    <div class="wrapper">
        <main>
            <h2 class="place">您现在的位置是：<a href="{% url 'blog:index' %}">网站首页</a>&gt; <a href="#">{{ title }}</a></h2>
            <div class="bloglist">
                <ul>
                    {% for article in post_list %}
                        <li><i class="blogpic"><a href="#"><img src="{{ article.image.url }}" alt=""> </a></i>
                            <dl>
                                <dt><a href="{% url 'blog:article_detail' article.slug %}"
                                       target="_blank">{{ article.title }}</a></dt>
                                <dd><span class="bloginfo">{{ article.summary }}...</span>
                                    <p class="timeinfo"><span class="lanmu"><a
                                            href="http://www.lmlblog.com/category/moban"
                                            target="_blank">{{ article.category }}</a></span><span
                                            class="date">{{ article.create_date }}</span></p>
                                    <a class="read" href="{% url 'blog:article_detail' article.slug %}">阅读更多</a></dd>
                            </dl>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {{ page_html|safe }}
{#            <div class="pagelist"><a title="Total record">&nbsp;<b>6</b> </a>&nbsp;&nbsp;&nbsp;<b>1</b>&nbsp;<a#}
{#                    href="">2</a>&nbsp;<a href="">3</a>&nbsp;<a href="">4</a>&nbsp;<a href="">5</a>&nbsp;<a#}
{#                    href="">6</a>&nbsp;<a#}
{#                    href="">下一页</a>&nbsp;<a href="">尾页</a></div>#}
        </main>
        {% include 'blog/sidebar.html' %}
    </div>
{% endblock content %}

article/templates/blog/time-line.html
{% extends "blog/base.html" %}
{% load blog_extras %}
{% block title %}
    时间轴
{% endblock title %}

{% block content %}
    <div class="wrapper">
        <main>
            <h2 class="place">您现在的位置是：<a href="{% url 'blog:index' %}">网站首页</a>&gt; <a href="#">时光轴</a></h2>
            <div class="timebox">
                <ul>
                    {% for article in articles %}

                        <li><span>{{ article.create_date | date:"Y-m-d" }}</span><i><a
                                href="{% url 'blog:article_detail' article.slug %}"
                                target="_blank">{{ article.title }}</a></i></li>
                    {% endfor %}
                </ul>
            </div>
        {{ page_html|safe }}
{#            <div class="pagelist"><a title="Total record">&nbsp;<b>6</b> </a>&nbsp;&nbsp;&nbsp;<b>1</b>&nbsp;<a#}
{#                    href="">2</a>&nbsp;<a href="">3</a>&nbsp;<a href="">4</a>&nbsp;<a href="">5</a>&nbsp;<a#}
{#                    href="">6</a>&nbsp;<a#}
{#                    href="">下一页</a>&nbsp;<a href="">尾页</a></div>#}
        </main>
        {% include 'blog/sidebar.html' %}
    </div>
{% endblock content %}